# Generated by Django 4.2 on 2023-05-26 11:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=100)),
                ('candidate_name', models.CharField(max_length=50)),
                ('father_name', models.CharField(max_length=50)),
                ('father_profession', models.CharField(choices=[('Imaam-khatib', 'Imaam-khatib'), ('Muazzin', 'Muazzin'), ('Accountant', 'Accountant'), ('Actor', 'Actor'), ('Doctor', 'Doctor'), ('Teacher', 'Teacher'), ('Writer', 'Writer'), ('Farmer', 'Farmer'), ('Engineer', 'Engineer'), ('Lawyer', 'Lawyer'), ('Business-person', 'Business-person'), ('Journalist', 'Journalist'), ('Banker', 'Banker'), ('Student', 'Student'), ('House-wife', 'House-wife'), ('Govt-employee', 'Govt-employee'), ('Private-company', 'Private-company'), ('probashi', 'probashi'), ('Others', 'Others')], max_length=50)),
                ('mother_name', models.CharField(max_length=50)),
                ('mother_profession', models.CharField(choices=[('Imaam-khatib', 'Imaam-khatib'), ('Muazzin', 'Muazzin'), ('Accountant', 'Accountant'), ('Actor', 'Actor'), ('Doctor', 'Doctor'), ('Teacher', 'Teacher'), ('Writer', 'Writer'), ('Farmer', 'Farmer'), ('Engineer', 'Engineer'), ('Lawyer', 'Lawyer'), ('Business-person', 'Business-person'), ('Journalist', 'Journalist'), ('Banker', 'Banker'), ('Student', 'Student'), ('House-wife', 'House-wife'), ('Govt-employee', 'Govt-employee'), ('Private-company', 'Private-company'), ('probashi', 'probashi'), ('Others', 'Others')], max_length=50)),
                ('birthday', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6)),
                ('height', models.CharField(max_length=10)),
                ('weight', models.CharField(max_length=10)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('O+', 'O+'), ('B+', 'B+'), ('AB+', 'AB+'), ('A-', 'A-'), ('O-', 'O-'), ('B-', 'B-'), ('AB-', 'AB-')], max_length=3)),
                ('skin_color', models.CharField(choices=[('Pale skin', 'Pale skin'), ('Fair skin', 'Fair skin'), ('Medium skin', 'Medium skin'), ('Olive skin', 'Olive skin'), ('Naturally brown skin', 'Naturally brown skin'), ('Very dark brown skin', 'Very dark brown skin')], max_length=20)),
                ('religion', models.CharField(choices=[('Islam', 'Islam'), ('Christianity', 'Christianity'), ('Buddhism', 'Buddhism'), ('Hinduism', 'Hinduism'), ('Judaism', 'Judaism'), ('Sikhism', 'Sikhism'), ('Zoroastrianism', 'Zoroastrianism'), ('Others religion', 'Others religion')], max_length=15)),
                ('marriage_status', models.CharField(choices=[('Never married', 'Never married'), ('Short divorced', 'Short divorced'), ('Divorced', 'Divorced'), ('Separated', 'Separated'), ('Widow', 'Widow'), ('Widower', 'Widower')], max_length=17)),
                ('education', models.CharField(max_length=50)),
                ('occupation', models.CharField(choices=[('Imaam-khatib', 'Imaam-khatib'), ('Muazzin', 'Muazzin'), ('Accountant', 'Accountant'), ('Actor', 'Actor'), ('Doctor', 'Doctor'), ('Teacher', 'Teacher'), ('Writer', 'Writer'), ('Farmer', 'Farmer'), ('Engineer', 'Engineer'), ('Lawyer', 'Lawyer'), ('Business-person', 'Business-person'), ('Journalist', 'Journalist'), ('Banker', 'Banker'), ('Student', 'Student'), ('House-wife', 'House-wife'), ('Govt-employee', 'Govt-employee'), ('Private-company', 'Private-company'), ('probashi', 'probashi'), ('Others', 'Others')], max_length=15)),
                ('present_address', models.TextField(blank=True, null=True)),
                ('permanent_address', models.TextField(blank=True, null=True)),
                ('Sister_brother_details', models.TextField(blank=True, null=True)),
                ('others', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('likes', models.ManyToManyField(blank=True, related_name='Advertisement_like', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Advertisements', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
