# Generated by Django 4.2 on 2023-05-26 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertisement',
            old_name='candidate_name',
            new_name='last_name',
        ),
        migrations.AddField(
            model_name='advertisement',
            name='frist_name',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
