# Generated by Django 4.2 on 2023-05-17 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='view_count',
            field=models.IntegerField(default=1),
        ),
    ]
