# Generated by Django 4.2 on 2023-05-21 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_remove_profile_follows_profile_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='contact_no',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='education',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='height',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('Never married', 'Never married'), ('Short divorced', 'Short divorced'), ('Divorced', 'Divorced'), ('Separated', 'Separated'), ('Widow', 'Widow'), ('Widower', 'Widower')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='occupation',
            field=models.CharField(blank=True, choices=[('Imaam-khatib', 'Imaam-khatib'), ('Muazzin', 'Muazzin'), ('Accountant', 'Accountant'), ('Actor', 'Actor'), ('Doctor', 'Doctor'), ('Teacher', 'Teacher'), ('Writer', 'Writer'), ('Farmer', 'Farmer'), ('Engineer', 'Engineer'), ('Lawyer', 'Lawyer'), ('Business-person', 'Business-person'), ('Journalist', 'Journalist'), ('Banker', 'Banker'), ('Student', 'Student'), ('House-wife', 'House-wife'), ('Govt-employee', 'Govt-employee'), ('Private-company', 'Private-company'), ('probashi', 'probashi'), ('Others', 'Others')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='permanent_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='present_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='religion',
            field=models.CharField(blank=True, choices=[('Islam', 'Islam'), ('Christianity', 'Christianity'), ('Buddhism', 'Buddhism'), ('Hinduism', 'Hinduism'), ('Judaism', 'Judaism'), ('Sikhism', 'Sikhism'), ('Zoroastrianism', 'Zoroastrianism'), ('Others religion', 'Others religion')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='weight',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
