# Generated by Django 4.2 on 2023-05-22 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_profile_birthday_profile_contact_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
    ]
