# Generated by Django 4.2 on 2023-05-24 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0008_whoprofileview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Whoprofileview',
        ),
    ]
